[versions]
coroutines = "1.10.2"
kotlin = "2.2.21"
moshi = "1.15.2"
okhttp = "5.3.2"
retrofit = "3.0.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.21" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }

[bundles]
logging = ["slf4j-api", "logback-classic"]
moshi = ["moshi", "moshi-kotlin"]
okhttp = ["okhttp"]
retrofit = ["retrofit", "retrofit-converter-moshi"]

[plugins]
dotenv = { id = "co.uzzu.dotenv.gradle", version = "4.0.0" }
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }
